// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sample_g_b
void sample_g_b(arma::mat& g, const arma::mat& g_free_ind, const arma::uvec& xi, const arma::mat& x_covariates, const arma::mat& ytp, const arma::mat& yfp, const arma::mat& beta_tp, const arma::mat& alpha_tp, const arma::mat& beta_fp, const arma::mat& alpha_fp, arma::vec& b_tp, arma::vec& b_fp, const arma::vec& e_tp, const arma::vec& e_fp, const arma::mat& e12, const double sig2_tp, const double sig2_fp, const double rho);
RcppExport SEXP _jsem_sample_g_b(SEXP gSEXP, SEXP g_free_indSEXP, SEXP xiSEXP, SEXP x_covariatesSEXP, SEXP ytpSEXP, SEXP yfpSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP b_tpSEXP, SEXP b_fpSEXP, SEXP e_tpSEXP, SEXP e_fpSEXP, SEXP e12SEXP, SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type g_free_ind(g_free_indSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_covariates(x_covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e_tp(e_tpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e_fp(e_fpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type e12(e12SEXP);
    Rcpp::traits::input_parameter< const double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< const double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    sample_g_b(g, g_free_ind, xi, x_covariates, ytp, yfp, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, e_tp, e_fp, e12, sig2_tp, sig2_fp, rho);
    return R_NilValue;
END_RCPP
}
// jsem_cpp
Rcpp::List jsem_cpp(arma::mat ytp, arma::mat yfp, arma::mat x_covariates, arma::vec b_tp, arma::vec b_fp, arma::mat g, arma::mat g_free_ind, double sig2_tp, double sig2_fp, double rho, arma::vec e_tp, arma::vec e_fp, arma::mat e12, arma::uvec xi, arma::mat beta_tp, arma::mat alpha_tp, arma::mat beta_fp, arma::mat alpha_fp, int mcmc_len, bool verbose);
RcppExport SEXP _jsem_jsem_cpp(SEXP ytpSEXP, SEXP yfpSEXP, SEXP x_covariatesSEXP, SEXP b_tpSEXP, SEXP b_fpSEXP, SEXP gSEXP, SEXP g_free_indSEXP, SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP, SEXP e_tpSEXP, SEXP e_fpSEXP, SEXP e12SEXP, SEXP xiSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP mcmc_lenSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates(x_covariatesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g_free_ind(g_free_indSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_tp(e_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_fp(e_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e12(e12SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc_len(mcmc_lenSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(jsem_cpp(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e_tp, e_fp, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose));
    return rcpp_result_gen;
END_RCPP
}
// jsem_cpp1
Rcpp::List jsem_cpp1(arma::mat ytp, arma::mat yfp, arma::mat x_covariates, arma::vec b_tp, arma::vec b_fp, arma::mat g, arma::mat g_free_ind, double sig2_tp, double sig2_fp, double rho, arma::mat e12, arma::uvec xi, arma::mat beta_tp, arma::mat alpha_tp, arma::mat beta_fp, arma::mat alpha_fp, int mcmc_len, bool verbose);
RcppExport SEXP _jsem_jsem_cpp1(SEXP ytpSEXP, SEXP yfpSEXP, SEXP x_covariatesSEXP, SEXP b_tpSEXP, SEXP b_fpSEXP, SEXP gSEXP, SEXP g_free_indSEXP, SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP, SEXP e12SEXP, SEXP xiSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP mcmc_lenSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates(x_covariatesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g_free_ind(g_free_indSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e12(e12SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc_len(mcmc_lenSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(jsem_cpp1(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose));
    return rcpp_result_gen;
END_RCPP
}
// jsem_multi_chains
Rcpp::List jsem_multi_chains(arma::mat ytp, arma::mat yfp, arma::mat x_covariates, arma::vec b_tp, arma::vec b_fp, arma::mat g, arma::mat g_free_ind, double sig2_tp, double sig2_fp, double rho, arma::uvec xi, arma::mat beta_tp, arma::mat alpha_tp, arma::mat beta_fp, arma::mat alpha_fp, int mcmc_len, int chains);
RcppExport SEXP _jsem_jsem_multi_chains(SEXP ytpSEXP, SEXP yfpSEXP, SEXP x_covariatesSEXP, SEXP b_tpSEXP, SEXP b_fpSEXP, SEXP gSEXP, SEXP g_free_indSEXP, SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP, SEXP xiSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP mcmc_lenSEXP, SEXP chainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates(x_covariatesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g_free_ind(g_free_indSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc_len(mcmc_lenSEXP);
    Rcpp::traits::input_parameter< int >::type chains(chainsSEXP);
    rcpp_result_gen = Rcpp::wrap(jsem_multi_chains(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, chains));
    return rcpp_result_gen;
END_RCPP
}
// getjsem_threads
int getjsem_threads();
RcppExport SEXP _jsem_getjsem_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getjsem_threads());
    return rcpp_result_gen;
END_RCPP
}
// setjsem_threads
int setjsem_threads(int threads);
RcppExport SEXP _jsem_setjsem_threads(SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(setjsem_threads(threads));
    return rcpp_result_gen;
END_RCPP
}
// sample_b_tp_c
arma::vec sample_b_tp_c(arma::vec b_tp, const arma::mat& ytp, const arma::uvec& xi, const arma::mat& x_covariates, const arma::mat& beta_tp, const arma::mat& alpha_tp, const arma::vec& e_tp, const arma::vec& e1);
RcppExport SEXP _jsem_sample_b_tp_c(SEXP b_tpSEXP, SEXP ytpSEXP, SEXP xiSEXP, SEXP x_covariatesSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP e_tpSEXP, SEXP e1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_covariates(x_covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e_tp(e_tpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e1(e1SEXP);
    rcpp_result_gen = Rcpp::wrap(sample_b_tp_c(b_tp, ytp, xi, x_covariates, beta_tp, alpha_tp, e_tp, e1));
    return rcpp_result_gen;
END_RCPP
}
// sample_b_fp_c
arma::vec sample_b_fp_c(arma::vec b_fp, const arma::mat& yfp, const arma::uvec& xi, const arma::mat& x_covariates, const arma::mat& beta_fp, const arma::mat& alpha_fp, const arma::vec& e_fp, const arma::vec& e2);
RcppExport SEXP _jsem_sample_b_fp_c(SEXP b_fpSEXP, SEXP yfpSEXP, SEXP xiSEXP, SEXP x_covariatesSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP e_fpSEXP, SEXP e2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_covariates(x_covariatesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e_fp(e_fpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e2(e2SEXP);
    rcpp_result_gen = Rcpp::wrap(sample_b_fp_c(b_fp, yfp, xi, x_covariates, beta_fp, alpha_fp, e_fp, e2));
    return rcpp_result_gen;
END_RCPP
}
// sample_b_linear_reg
arma::vec sample_b_linear_reg(arma::vec e_tp1, arma::vec e_tp2, arma::vec e_fp2, arma::mat x_covariates1, arma::mat x_covariates2, arma::vec b_tp, arma::vec b_fp, double sig2_tp, double sig2_fp, double rho);
RcppExport SEXP _jsem_sample_b_linear_reg(SEXP e_tp1SEXP, SEXP e_tp2SEXP, SEXP e_fp2SEXP, SEXP x_covariates1SEXP, SEXP x_covariates2SEXP, SEXP b_tpSEXP, SEXP b_fpSEXP, SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type e_tp1(e_tp1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_tp2(e_tp2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_fp2(e_fp2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates1(x_covariates1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates2(x_covariates2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_b_linear_reg(e_tp1, e_tp2, e_fp2, x_covariates1, x_covariates2, b_tp, b_fp, sig2_tp, sig2_fp, rho));
    return rcpp_result_gen;
END_RCPP
}
// sample_e_tp_c
arma::vec sample_e_tp_c(arma::vec e_tp, arma::mat ytp, arma::uvec xi, arma::vec b_tp, double sig2_tp, arma::mat beta_tp, arma::mat alpha_tp, arma::mat x_covariates);
RcppExport SEXP _jsem_sample_e_tp_c(SEXP e_tpSEXP, SEXP ytpSEXP, SEXP xiSEXP, SEXP b_tpSEXP, SEXP sig2_tpSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP x_covariatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type e_tp(e_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates(x_covariatesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_e_tp_c(e_tp, ytp, xi, b_tp, sig2_tp, beta_tp, alpha_tp, x_covariates));
    return rcpp_result_gen;
END_RCPP
}
// sample_e_fp_c
arma::vec sample_e_fp_c(arma::vec e_fp, arma::mat yfp, arma::uvec xi, arma::vec b_fp, double sig2_fp, arma::mat beta_fp, arma::mat alpha_fp, arma::mat x_covariates);
RcppExport SEXP _jsem_sample_e_fp_c(SEXP e_fpSEXP, SEXP yfpSEXP, SEXP xiSEXP, SEXP b_fpSEXP, SEXP sig2_fpSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP x_covariatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type e_fp(e_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates(x_covariatesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_e_fp_c(e_fp, yfp, xi, b_fp, sig2_fp, beta_fp, alpha_fp, x_covariates));
    return rcpp_result_gen;
END_RCPP
}
// sample_e12_c
arma::mat sample_e12_c(arma::mat e12, arma::mat ytp, arma::mat yfp, arma::uvec xi, arma::mat beta_tp, arma::mat alpha_tp, arma::mat beta_fp, arma::mat alpha_fp, double sig2_tp, double sig2_fp, double rho, arma::vec b_tp, arma::vec b_fp, arma::mat x_covariates);
RcppExport SEXP _jsem_sample_e12_c(SEXP e12SEXP, SEXP ytpSEXP, SEXP yfpSEXP, SEXP xiSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP, SEXP b_tpSEXP, SEXP b_fpSEXP, SEXP x_covariatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type e12(e12SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates(x_covariatesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_e12_c(e12, ytp, yfp, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, sig2_tp, sig2_fp, rho, b_tp, b_fp, x_covariates));
    return rcpp_result_gen;
END_RCPP
}
// sample_g_c
arma::mat sample_g_c(arma::mat g, const arma::mat& g_free_ind, const arma::uvec& xi, const arma::mat& x_covariates);
RcppExport SEXP _jsem_sample_g_c(SEXP gSEXP, SEXP g_free_indSEXP, SEXP xiSEXP, SEXP x_covariatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type g_free_ind(g_free_indSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x_covariates(x_covariatesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_g_c(g, g_free_ind, xi, x_covariates));
    return rcpp_result_gen;
END_RCPP
}
// sample_sig2_tp_c
double sample_sig2_tp_c(double sig2_tp, double sig2_fp, double rho, arma::vec e_tp, arma::mat e12, arma::uvec xi);
RcppExport SEXP _jsem_sample_sig2_tp_c(SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP, SEXP e_tpSEXP, SEXP e12SEXP, SEXP xiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_tp(e_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e12(e12SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_sig2_tp_c(sig2_tp, sig2_fp, rho, e_tp, e12, xi));
    return rcpp_result_gen;
END_RCPP
}
// sample_sig2_fp_c
double sample_sig2_fp_c(double sig2_tp, double sig2_fp, double rho, arma::vec e_fp, arma::mat e12, arma::uvec xi);
RcppExport SEXP _jsem_sample_sig2_fp_c(SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP rhoSEXP, SEXP e_fpSEXP, SEXP e12SEXP, SEXP xiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_fp(e_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e12(e12SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type xi(xiSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_sig2_fp_c(sig2_tp, sig2_fp, rho, e_fp, e12, xi));
    return rcpp_result_gen;
END_RCPP
}
// sample_rho_c
double sample_rho_c(double rho, const arma::uvec& xi, double sig2_tp, double sig2_fp, const arma::mat& e12);
RcppExport SEXP _jsem_sample_rho_c(SEXP rhoSEXP, SEXP xiSEXP, SEXP sig2_tpSEXP, SEXP sig2_fpSEXP, SEXP e12SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_tp(sig2_tpSEXP);
    Rcpp::traits::input_parameter< double >::type sig2_fp(sig2_fpSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type e12(e12SEXP);
    rcpp_result_gen = Rcpp::wrap(sample_rho_c(rho, xi, sig2_tp, sig2_fp, e12));
    return rcpp_result_gen;
END_RCPP
}
// sample_Sigma_new
arma::mat sample_Sigma_new(const arma::mat& e12);
RcppExport SEXP _jsem_sample_Sigma_new(SEXP e12SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type e12(e12SEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Sigma_new(e12));
    return rcpp_result_gen;
END_RCPP
}
// sample_xi
arma::uvec sample_xi(arma::mat x_covariates, arma::mat g, arma::mat beta_tp, arma::mat alpha_tp, arma::mat beta_fp, arma::mat alpha_fp, arma::mat ytp, arma::vec b_tp, arma::vec e_tp, arma::mat yfp, arma::vec b_fp, arma::vec e_fp, arma::mat e12);
RcppExport SEXP _jsem_sample_xi(SEXP x_covariatesSEXP, SEXP gSEXP, SEXP beta_tpSEXP, SEXP alpha_tpSEXP, SEXP beta_fpSEXP, SEXP alpha_fpSEXP, SEXP ytpSEXP, SEXP b_tpSEXP, SEXP e_tpSEXP, SEXP yfpSEXP, SEXP b_fpSEXP, SEXP e_fpSEXP, SEXP e12SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x_covariates(x_covariatesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_tp(beta_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_tp(alpha_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type beta_fp(beta_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_fp(alpha_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ytp(ytpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_tp(b_tpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_tp(e_tpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yfp(yfpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b_fp(b_fpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type e_fp(e_fpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e12(e12SEXP);
    rcpp_result_gen = Rcpp::wrap(sample_xi(x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, e_tp, yfp, b_fp, e_fp, e12));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jsem_sample_g_b", (DL_FUNC) &_jsem_sample_g_b, 18},
    {"_jsem_jsem_cpp", (DL_FUNC) &_jsem_jsem_cpp, 20},
    {"_jsem_jsem_cpp1", (DL_FUNC) &_jsem_jsem_cpp1, 18},
    {"_jsem_jsem_multi_chains", (DL_FUNC) &_jsem_jsem_multi_chains, 17},
    {"_jsem_getjsem_threads", (DL_FUNC) &_jsem_getjsem_threads, 0},
    {"_jsem_setjsem_threads", (DL_FUNC) &_jsem_setjsem_threads, 1},
    {"_jsem_sample_b_tp_c", (DL_FUNC) &_jsem_sample_b_tp_c, 8},
    {"_jsem_sample_b_fp_c", (DL_FUNC) &_jsem_sample_b_fp_c, 8},
    {"_jsem_sample_b_linear_reg", (DL_FUNC) &_jsem_sample_b_linear_reg, 10},
    {"_jsem_sample_e_tp_c", (DL_FUNC) &_jsem_sample_e_tp_c, 8},
    {"_jsem_sample_e_fp_c", (DL_FUNC) &_jsem_sample_e_fp_c, 8},
    {"_jsem_sample_e12_c", (DL_FUNC) &_jsem_sample_e12_c, 14},
    {"_jsem_sample_g_c", (DL_FUNC) &_jsem_sample_g_c, 4},
    {"_jsem_sample_sig2_tp_c", (DL_FUNC) &_jsem_sample_sig2_tp_c, 6},
    {"_jsem_sample_sig2_fp_c", (DL_FUNC) &_jsem_sample_sig2_fp_c, 6},
    {"_jsem_sample_rho_c", (DL_FUNC) &_jsem_sample_rho_c, 5},
    {"_jsem_sample_Sigma_new", (DL_FUNC) &_jsem_sample_Sigma_new, 1},
    {"_jsem_sample_xi", (DL_FUNC) &_jsem_sample_xi, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_jsem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
