# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_g_b <- function(g, g_free_ind, xi, x_covariates, ytp, yfp, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, e_tp, e_fp, e12, sig2_tp, sig2_fp, rho) {
    invisible(.Call('_jsem_sample_g_b', PACKAGE = 'jsem', g, g_free_ind, xi, x_covariates, ytp, yfp, beta_tp, alpha_tp, beta_fp, alpha_fp, b_tp, b_fp, e_tp, e_fp, e12, sig2_tp, sig2_fp, rho))
}

#' @export
jsem_cpp <- function(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e_tp, e_fp, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose = FALSE) {
    .Call('_jsem_jsem_cpp', PACKAGE = 'jsem', ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e_tp, e_fp, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose)
}

#' @export
jsem_cpp1 <- function(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose = FALSE) {
    .Call('_jsem_jsem_cpp1', PACKAGE = 'jsem', ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, e12, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, verbose)
}

jsem_multi_chains <- function(ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, chains = 1L) {
    .Call('_jsem_jsem_multi_chains', PACKAGE = 'jsem', ytp, yfp, x_covariates, b_tp, b_fp, g, g_free_ind, sig2_tp, sig2_fp, rho, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, mcmc_len, chains)
}

#' @export 
getjsem_threads <- function() {
    .Call('_jsem_getjsem_threads', PACKAGE = 'jsem')
}

#' @export 
setjsem_threads <- function(threads) {
    .Call('_jsem_setjsem_threads', PACKAGE = 'jsem', threads)
}

sample_b_tp_c <- function(b_tp, ytp, xi, x_covariates, beta_tp, alpha_tp, e_tp, e1) {
    .Call('_jsem_sample_b_tp_c', PACKAGE = 'jsem', b_tp, ytp, xi, x_covariates, beta_tp, alpha_tp, e_tp, e1)
}

sample_b_fp_c <- function(b_fp, yfp, xi, x_covariates, beta_fp, alpha_fp, e_fp, e2) {
    .Call('_jsem_sample_b_fp_c', PACKAGE = 'jsem', b_fp, yfp, xi, x_covariates, beta_fp, alpha_fp, e_fp, e2)
}

sample_b_linear_reg <- function(e_tp1, e_tp2, e_fp2, x_covariates1, x_covariates2, b_tp, b_fp, sig2_tp, sig2_fp, rho) {
    .Call('_jsem_sample_b_linear_reg', PACKAGE = 'jsem', e_tp1, e_tp2, e_fp2, x_covariates1, x_covariates2, b_tp, b_fp, sig2_tp, sig2_fp, rho)
}

sample_e_tp_c <- function(e_tp, ytp, xi, b_tp, sig2_tp, beta_tp, alpha_tp, x_covariates) {
    .Call('_jsem_sample_e_tp_c', PACKAGE = 'jsem', e_tp, ytp, xi, b_tp, sig2_tp, beta_tp, alpha_tp, x_covariates)
}

sample_e_fp_c <- function(e_fp, yfp, xi, b_fp, sig2_fp, beta_fp, alpha_fp, x_covariates) {
    .Call('_jsem_sample_e_fp_c', PACKAGE = 'jsem', e_fp, yfp, xi, b_fp, sig2_fp, beta_fp, alpha_fp, x_covariates)
}

sample_e12_c <- function(e12, ytp, yfp, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, sig2_tp, sig2_fp, rho, b_tp, b_fp, x_covariates) {
    .Call('_jsem_sample_e12_c', PACKAGE = 'jsem', e12, ytp, yfp, xi, beta_tp, alpha_tp, beta_fp, alpha_fp, sig2_tp, sig2_fp, rho, b_tp, b_fp, x_covariates)
}

sample_g_c <- function(g, g_free_ind, xi, x_covariates) {
    .Call('_jsem_sample_g_c', PACKAGE = 'jsem', g, g_free_ind, xi, x_covariates)
}

sample_sig2_tp_c <- function(sig2_tp, sig2_fp, rho, e_tp, e12, xi) {
    .Call('_jsem_sample_sig2_tp_c', PACKAGE = 'jsem', sig2_tp, sig2_fp, rho, e_tp, e12, xi)
}

sample_sig2_fp_c <- function(sig2_tp, sig2_fp, rho, e_fp, e12, xi) {
    .Call('_jsem_sample_sig2_fp_c', PACKAGE = 'jsem', sig2_tp, sig2_fp, rho, e_fp, e12, xi)
}

sample_rho_c <- function(rho, xi, sig2_tp, sig2_fp, e12) {
    .Call('_jsem_sample_rho_c', PACKAGE = 'jsem', rho, xi, sig2_tp, sig2_fp, e12)
}

#' @export
sample_Sigma_new <- function(e12) {
    .Call('_jsem_sample_Sigma_new', PACKAGE = 'jsem', e12)
}

sample_xi <- function(x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, e_tp, yfp, b_fp, e_fp, e12) {
    .Call('_jsem_sample_xi', PACKAGE = 'jsem', x_covariates, g, beta_tp, alpha_tp, beta_fp, alpha_fp, ytp, b_tp, e_tp, yfp, b_fp, e_fp, e12)
}

